FROM rust:slim AS builder
WORKDIR /usr/src/adtech
COPY . .
RUN cargo build --release --bin dsp-server

FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/adtech/target/release/dsp-server /app/dsp-server
EXPOSE 8085
CMD ["./dsp-server"]
