FROM rust:slim AS builder
WORKDIR /usr/src/adtech
COPY . .
RUN cargo build --release --bin campaign-api

FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/adtech/target/release/campaign-api /app/campaign-api
EXPOSE 8080
CMD ["./campaign-api"]
