[package]
name = "rtb-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
core-models = { version = "0.1.0", path = "../../libs/core-models" }
kafka-utils = { version = "0.1.0", path = "../../libs/kafka-utils" }
rskafka.workspace = true
redis.workspace = true
redis-utils = { version = "0.1.0", path = "../../libs/redis-utils" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
