[package]
name = "reconciliation-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dotenvy = { workspace = true }
sqlx = { workspace = true }
rskafka = { workspace = true }
uuid = { version = "1.7", features = ["v4"] }
core-models = { version = "0.1.0", path = "../../libs/core-models" }