# ==========================================
# 3. REDPANDA (KAFKA MESSAGE BROKER)
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: redpanda
spec:
  ports:
    - name: kafka
      port: 9092
    - name: admin
      port: 9644
  selector:
    app: redpanda
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  serviceName: "redpanda"
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:latest
          command:
            - rpk
            - redpanda
            - start
          args:
            - --mode=dev-container
            - --smp=1
            - --memory=1G
            - --kafka-addr=internal://0.0.0.0:9092
            - --advertise-kafka-addr=internal://redpanda:9092
          ports:
            - containerPort: 9092
            - containerPort: 9644
          volumeMounts:
            - name: redpanda-data
              mountPath: /var/lib/redpanda/data
  volumeClaimTemplates:
    - metadata:
        name: redpanda-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi