[package]
name = "audience-edge"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
axum-extra = { version = "0.9", features = ["cookie"] }
serde = { workspace = true }
serde_json = { workspace = true }
dotenvy = { workspace = true }
redis = { version = "0.24", features = ["tokio-comp"] }
uuid = { version = "1.7", features = ["v4", "fast-rng"] }
url = "2"